import { useState } from 'react'
import { Search, AlertTriangle, ArrowRight, Zap, IndianRupee } from 'lucide-react'
import Layout from '../components/Layout'
import { DemoBadge, SectionHeader, Pill, Modal } from '../components/UI'
import { ANOMALIES } from '../data/demoData'

const severityTone = { High: 'high', Medium: 'medium', Low: 'low' }

export default function WasteDetective() {
  const [active, setActive] = useState(null)

  return (
    <Layout title="Energy Waste Detective" subtitle="Where energy is likely being wasted, and why">
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-danger/10 ring-1 ring-danger/25 grid place-items-center">
            <Search size={15} className="text-danger" />
          </div>
          <p className="text-[13px] text-mist-500">{ANOMALIES.length} issues flagged from today's simulated readings</p>
        </div>
        <DemoBadge />
      </div>

      <div className="space-y-4">
        {ANOMALIES.map((a) => (
          <div key={a.id} className="panel p-5 md:p-6">
            <div className="flex items-start justify-between gap-4 flex-wrap">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-xl bg-danger/10 ring-1 ring-danger/25 grid place-items-center shrink-0 mt-0.5">
                  <AlertTriangle size={17} className="text-danger" />
                </div>
                <div>
                  <h3 className="font-display font-semibold text-[16px] text-mist-100">{a.equipment}</h3>
                  <p className="text-[13px] text-mist-500">{a.title}</p>
                </div>
              </div>
              <Pill tone={severityTone[a.severity]}>{a.severity} severity</Pill>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5">
              <Metric label="Current" value={`${a.current} kWh/h`} />
              <Metric label="Expected" value={`${a.expected} kWh/h`} />
              <Metric label="Deviation" value={`+${a.deviationPct}%`} tone="danger" />
              <Metric label="Monthly Waste" value={`${a.monthlyWasteKwh} kWh`} tone="amber" />
            </div>

            <div className="flex items-center justify-between mt-5 flex-wrap gap-3">
              <div className="flex items-center gap-2 text-[12.5px] text-mist-500">
                <IndianRupee size={14} className="text-amber-400" />
                Potential monthly cost: <span className="text-mist-100 font-medium font-mono-num">₹{a.monthlyCostInr}</span>
              </div>
              <button
                onClick={() => setActive(a)}
                className="inline-flex items-center gap-1.5 text-[12.5px] font-semibold text-amber-400 hover:text-amber-300 transition-colors"
              >
                Investigate
                <ArrowRight size={14} />
              </button>
            </div>
          </div>
        ))}
      </div>

      <Modal open={!!active} onClose={() => setActive(null)} title={active ? `Investigate: ${active.equipment}` : ''}>
        {active && (
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Pill tone={severityTone[active.severity]}>{active.severity} severity</Pill>
              <span className="text-[12px] text-mist-500">{active.title}</span>
            </div>

            <div>
              <p className="text-[11.5px] font-semibold uppercase tracking-wide text-mist-500 mb-1">Possible Cause</p>
              <p className="text-[13.5px] text-mist-200 leading-relaxed">{active.cause}</p>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <Metric label="Current draw" value={`${active.current} kWh/h`} />
              <Metric label="Expected draw" value={`${active.expected} kWh/h`} />
              <Metric label="Monthly waste" value={`${active.monthlyWasteKwh} kWh`} tone="amber" />
              <Metric label="Monthly cost" value={`₹${active.monthlyCostInr}`} tone="amber" />
            </div>

            <div className="rounded-xl bg-graphite-800/60 border border-graphite-700 p-4 flex items-start gap-3">
              <Zap size={16} className="text-teal-400 shrink-0 mt-0.5" />
              <p className="text-[12.5px] text-mist-400 leading-relaxed">
                This diagnosis is generated by the  's rule-based engine against simulated demo data — it is not a definitive physical fault reading from connected hardware.
              </p>
            </div>

            <button
              onClick={() => setActive(null)}
              className="w-full bg-graphite-700 hover:bg-graphite-600 text-mist-100 text-[13px] font-medium rounded-xl py-2.5 transition-colors"
            >
              Close
            </button>
          </div>
        )}
      </Modal>
    </Layout>
  )
}

function Metric({ label, value, tone }) {
  const toneClass = tone === 'danger' ? 'text-danger' : tone === 'amber' ? 'text-amber-400' : 'text-mist-100'
  return (
    <div className="rounded-xl bg-graphite-800/60 border border-graphite-700 px-3.5 py-3">
      <p className="text-[10.5px] text-mist-500 mb-1">{label}</p>
      <p className={`font-mono-num text-[15px] font-semibold ${toneClass}`}>{value}</p>
    </div>
  )
}
